name: TF
channels:
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37he774522_1000
  - ca-certificates=2020.6.24=0
  - cachetools=4.1.0=py_1
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - colorama=0.4.3=py_0
  - comtypes=1.1.7=py37_0
  - cryptography=2.9.2=py37h7a1dbc1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cudnn=7.6.5=cuda10.1_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - freetype=2.10.2=hd328e21_0
  - google-auth=1.17.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - graphviz=2.38=hfd603c8_2
  - grpcio=1.27.2=py37h351948d_0
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=216
  - ipykernel=5.3.3=py37h5ca1d4c_0
  - ipython=7.16.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.1=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py37_1
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37h74a9793_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.12.3=h7bd577a_0
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h64f37c6_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.1=216
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.1.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py37_1
  - nbformat=5.0.7=py_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.5=py37h6530119_0
  - numpy-base=1.18.5=py37hc3f5095_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1g=he774522_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=py_0
  - pandas=1.0.5=py37h47e9c7a_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=py37_1001
  - pip=20.1.1=py37_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.12.3=py37h33f27b4_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pydot=1.4.1=py37_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pyrsistent=0.16.0=py37he774522_0
  - pysocks=1.7.1=py37_1
  - python=3.7.7=h81c818b_4
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyzmq=19.0.1=py37ha925a31_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scipy=1.4.1=py37h9439919_0
  - send2trash=1.5.0=py37_0
  - setuptools=49.2.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h2a8f88b_0
  - swig=3.0.12=h047fa9f_3
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=gpu_py37h7db9008_0
  - tensorflow-base=2.1.0=gpu_py37h55f5790_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - tensorflow-probability=0.8.0=py_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tornado=6.0.4=py37he774522_1
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py37he774522_1
  - xlrd=1.2.0=py37_0
  - zeromq=4.3.2=ha925a31_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - atari-py==0.2.6
    - box2d-py==2.3.8
    - cloudpickle==1.3.0
    - cython==0.29.21
    - dill==0.3.1.1
    - dm-tree==0.1.5
    - future==0.18.2
    - gast==0.3.3
    - glfw==1.12.0
    - gym==0.17.2
    - imageio==2.9.0
    - joblib==0.16.0
    - keras==2.4.3
    - lockfile==0.12.2
    - multiprocess==0.70.9
    - opencv-python==4.3.0.36
    - pillow==7.2.0
    - pox==0.2.7
    - ppft==1.6.6.1
    - pyglet==1.5.0
    - pyyaml==5.3.1
    - stable-baselines==2.10.0
prefix: C:\Users\meatrobot\miniconda3\envs\TF
